### ISSUE TITLE
能否设置幅度区间

### ISSUE THREAD

**Issue by kallenGao** [gaoli/GLChart#1]
你好，我想问下如果我的数据波动得比较小的话，都是在0.8到1.1范围之内，而这个都是从0开始，所以折线图看起来的波动太小，能不能给个区间设置波动幅度，谢谢

**Comment by gaoli** [comment]
更新 1.1.2 版本，添加 `chartData.isYAxisStartFromZero = NO` 即可：）

**Comment by kallenGao** [comment]
谢谢了，效果能看到了
